services:
  postgres:
    image: postgres
    container_name: task-tracer-db
    ports:
      - 5433:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=task-tracer
    networks:
      - task_tracer_network
    volumes:
      - pg:/var/lib/postgresql/data

  back-end:
    container_name: task_tracer_api
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@task-tracer-db:5432/task-tracer-db?schema=public
    build: .
    ports:
      - 3000:3000
    networks:
      - task_tracer_network
    depends_on:
      - postgres

volumes:
  pg:

networks:
  task_tracer_network:
    name: task_tracer_network
