services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 5433:5432
    environment:
      - POSTGRES_PASSWORD=postgres
    networks:
      - task_tracer_network
    volumes:
      - pg:/var/lib/postgresql/data

  back-end:
    container_name: task_tracer_api
    env_file:
      - .env
    build: .
    ports:
      - 3000:3000
    networks:
      - task_tracer_network
    depends_on:
      - postgres

volumes:
  pg:

networks:
  task_tracer_network:
    name: task_tracer_network
